/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.ProyectoBiblioteca.frames.Compra;

import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.CompraDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.LibroCompraDAO;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Compra;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.LibroCompra;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Garnios
 */
public class MostrarCompraFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarCompraFrame
     */
    public MostrarCompraFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        compraTable = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        compraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(compraTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            List<Compra> a = new CompraDAO().getCompras();
            List<LibroCompra> o = new LibroCompraDAO().getLibroCompras();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("id Venta");
            model.addColumn("Nro Boleta");
            model.addColumn("Rut Distribuidor");
            model.addColumn("Rut Trabajador");
            model.addColumn("Nro Serie libro");
            for (Compra p     : a) {
                Object[] fila = new Object[5];
                fila[0] = p.getId();
                fila[1] = p.getFolioFact();
                fila[2] = p.getDistribuidorRut();
                fila[3] = p.getTrabajadorRut();
                for (LibroCompra   g : o) {
                    if(g.getIdCompra()== p.getId()){
                        fila[4] = g.getIdLibro();
                    }
                }
               
                model.addRow(fila);
            }
            this.compraTable.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la ventana");
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable compraTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
