/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.ProyectoBiblioteca.frame.SistemaVenta;

import cl.inacap.ProyectoBibliotecaModel.DAO.LibroDAO.LibroDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.ClienteDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.TrabajadorDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.BoletaDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.LibroVentaDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.TipoDePagoDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.VentaDAO;
import cl.inacap.ProyectoBibliotecaModel.DTO.Libro.Libro;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Cliente;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Trabajador;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Boleta;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.LibroVenta;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.TipoDePago;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Venta;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Garnios
 */
public class IngresarSistemaVentaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresarSistemaVentaFrame
     */
    public IngresarSistemaVentaFrame() {
        initComponents();
        this.VenderBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nroBoletaTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechTxt = new javax.swing.JTextField();
        horaTxt = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calcularBtn = new javax.swing.JButton();
        VenderBtn = new javax.swing.JButton();
        libroCbx = new javax.swing.JComboBox<>();
        clienCbx = new javax.swing.JComboBox<>();
        trabCbx = new javax.swing.JComboBox<>();
        metPagCbx = new javax.swing.JComboBox<>();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú de Ventas");

        jLabel2.setText("Metodo de pago");

        jLabel3.setText("Fecha");

        jLabel4.setText("Hora");

        jLabel5.setText("Boleta Nro:");

        nroBoletaTxt.setEditable(false);

        jLabel6.setText("Libro:");

        jLabel7.setText("Cliente:");

        jLabel8.setText("Trabajador:");

        fechTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechTxtActionPerformed(evt);
            }
        });

        total.setEditable(false);

        jLabel9.setText("Total a pagar:");

        calcularBtn.setText("Calcular");
        calcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBtnActionPerformed(evt);
            }
        });

        VenderBtn.setText("Vender");
        VenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nroBoletaTxt)
                            .addComponent(fechTxt)
                            .addComponent(horaTxt)
                            .addComponent(libroCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clienCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trabCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(metPagCbx, 0, 210, Short.MAX_VALUE))
                        .addGap(169, 169, 169))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calcularBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(VenderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroBoletaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(metPagCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(horaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(libroCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clienCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(trabCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(calcularBtn))
                .addGap(18, 18, 18)
                .addComponent(VenderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderBtnActionPerformed
        // TODO add your handling code here:

        try {
            List<Boleta> bols = new BoletaDAO().getBoletas();
            List<Venta> vens = new VentaDAO().getVentas();
            int idBoleta = 0, idVenta = 0;
            for (Boleta p : bols) {
                idBoleta = p.getFolio() + 1;
            }
            for (Venta p : vens) {
                idVenta = p.getId() + 1;
            }
            //BOLETA
            Libro k = (Libro) this.libroCbx.getSelectedItem();
            int precioNeto = k.getPrecio();
            int precIva = precioNeto + (int) ((float) ((precioNeto) * 0.19));
            int costIva = (int) ((float) ((precioNeto) * 0.19));
            String fecVen = this.fechTxt.getText().trim();
            String hora = this.horaTxt.getText().trim();
            int iva = 19;
            TipoDePago s = (TipoDePago) this.metPagCbx.getSelectedItem();
            int idTip = s.getIdPago();

            Boleta p = new Boleta();
            p.setFolio(idBoleta);
            p.setPrecioNeto(precioNeto);
            p.setPrecioIVA(precIva);
            p.setCostoIVA(costIva);
            p.setFechaVenta(fecVen);
            p.setHoraVenta(hora);
            p.setIva(iva);
            p.setTipoPagoID(idTip);

            new BoletaDAO().ingresarBoleta(p);

            //Venta
            Trabajador y = (Trabajador) this.trabCbx.getSelectedItem();
            Cliente cl = (Cliente) this.clienCbx.getSelectedItem();
            int idTrab= y.getRut();
            int idClie = cl.getRut();

            Venta v = new Venta();
            v.setId(idVenta);
            v.setFolioBoleta(idBoleta);
            v.setClienteRut(idClie);
            v.setTrabajadorRut(idTrab);
            
            new VentaDAO().ingresarVenta(v);
            //LibroVenta
            int idLib = k.getIdSerie();
            LibroVenta h =new LibroVenta();
            h.setIdLibro(idLib);
            h.setIdVenta(idVenta);
            
            new LibroVentaDAO().ingresarLibroVenta(h);

            
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ingresado OK");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Ingresar una boleta");
        }


    }//GEN-LAST:event_VenderBtnActionPerformed

    private void fechTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechTxtActionPerformed

    private void calcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBtnActionPerformed
        // TODO add your handling code here:
        Libro l = (Libro) this.libroCbx.getSelectedItem();
        int prec = l.getPrecio();
        int total = prec + (int) ((float) ((prec) * 0.19));
        this.total.setText(total + "");
        this.VenderBtn.setEnabled(true);
    }//GEN-LAST:event_calcularBtnActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        List<Cliente> clins = new ClienteDAO().getClientes();
        this.clienCbx.removeAllItems();
        for (Cliente p : clins) {
            this.clienCbx.addItem(p);
        }
        List<Libro> s = new LibroDAO().getLibros();
        this.libroCbx.removeAllItems();
        for (Libro p : s) {
            this.libroCbx.addItem(p);
        }
        List<Trabajador> f = new TrabajadorDAO().getTrabajadores();
        this.trabCbx.removeAllItems();
        for (Trabajador p : f) {
            this.trabCbx.addItem(p);
        }
        List<TipoDePago> e = new TipoDePagoDAO().getTiposPagos();
        this.metPagCbx.removeAllItems();
        for (TipoDePago p : e) {
            this.metPagCbx.addItem(p);
        }
        List<Boleta> bols = new BoletaDAO().getBoletas();
        for (Boleta p : bols) {
                this.nroBoletaTxt.setText((p.getFolio()+1)+"");
            }
        
 
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VenderBtn;
    private javax.swing.JButton calcularBtn;
    private javax.swing.JComboBox<Cliente> clienCbx;
    private javax.swing.JTextField fechTxt;
    private javax.swing.JTextField horaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<Libro> libroCbx;
    private javax.swing.JComboBox<TipoDePago> metPagCbx;
    private javax.swing.JTextField nroBoletaTxt;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<Trabajador> trabCbx;
    // End of variables declaration//GEN-END:variables
}
