/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.ProyectoBiblioteca.frame.SistemaCompra;

import cl.inacap.ProyectoBibliotecaModel.DAO.LibroDAO.LibroDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.DistribuidorDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.TrabajadorDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.CompraDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.FacturaDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.LibroCompraDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.TipoDePagoDAO;
import cl.inacap.ProyectoBibliotecaModel.DTO.Libro.Libro;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Distribuidor;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Trabajador;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Compra;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Factura;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.LibroCompra;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.TipoDePago;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Garnios
 */
public class SistemaCompraFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SistemaCompraFrame
     */
    public SistemaCompraFrame() {
        initComponents();
        this.compraBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nroFactTxt = new javax.swing.JTextField();
        metPagCbx = new javax.swing.JComboBox<>();
        fechTxt = new javax.swing.JTextField();
        horTxt = new javax.swing.JTextField();
        libCbx = new javax.swing.JComboBox<>();
        distCbx = new javax.swing.JComboBox<>();
        trabCbx = new javax.swing.JComboBox<>();
        totaTxt = new javax.swing.JTextField();
        calcBtn = new javax.swing.JButton();
        compraBtn = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Compras");

        jLabel2.setText("Nro Factura");

        jLabel3.setText("Metodo de Pago");

        jLabel4.setText("Fecha");

        jLabel5.setText("Hora");

        jLabel6.setText("Libro");

        jLabel7.setText("Distribuidor");

        jLabel8.setText("Trabajador");

        nroFactTxt.setEditable(false);
        nroFactTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nroFactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroFactTxtActionPerformed(evt);
            }
        });

        totaTxt.setEditable(false);
        totaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        calcBtn.setText("Calcular");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        compraBtn.setText("Comprar");
        compraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(libCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nroFactTxt)
                                    .addComponent(metPagCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechTxt)
                                    .addComponent(horTxt)
                                    .addComponent(distCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trabCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(totaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(compraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nroFactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(metPagCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fechTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(libCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(distCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(trabCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(compraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nroFactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroFactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nroFactTxtActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        List<TipoDePago> clins = new TipoDePagoDAO().getTiposPagos();
        this.metPagCbx.removeAllItems();
        for (TipoDePago p : clins) {
            this.metPagCbx.addItem(p);
        }
        List<Libro> s = new LibroDAO().getLibros();
        this.libCbx.removeAllItems();
        for (Libro p : s) {
            this.libCbx.addItem(p);
        }
        List<Distribuidor> f = new DistribuidorDAO().getDistribuidores();
        this.distCbx.removeAllItems();
        for (Distribuidor p : f) {
            this.distCbx.addItem(p);
        }
        List<Trabajador> e = new TrabajadorDAO().getTrabajadores();
        this.trabCbx.removeAllItems();
        for (Trabajador p : e) {
            this.trabCbx.addItem(p);
        }
        List<Factura> bols = new FacturaDAO().getFacturas();
        for (Factura p : bols) {
                this.nroFactTxt.setText((p.getFolio()+1)+"");
            }
    }//GEN-LAST:event_formInternalFrameOpened

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        // TODO add your handling code here:
        Libro l = (Libro) this.libCbx.getSelectedItem();
        int prec = l.getPrecio();
        int total = (prec - (int) ((float) ((prec) * 0.30)));
        this.totaTxt.setText(total + "");
        this.compraBtn.setEnabled(true);
    }//GEN-LAST:event_calcBtnActionPerformed

    private void compraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraBtnActionPerformed
        // TODO add your handling code here:
        try {
            List<Factura> bols = new FacturaDAO().getFacturas();
            List<Compra> vens = new CompraDAO().getCompras();
            int idFact = 0, idCompra = 0;
            for (Factura p : bols) {
                idFact = p.getFolio() + 1;
            }
            for (Compra p : vens) {
                idCompra = p.getId() + 1;
            }
            //BOLETA
            Libro k = (Libro) this.libCbx.getSelectedItem();
            int precioNeto = k.getPrecio();
            int prectot = precioNeto - (int) ((float) ((precioNeto) * 0.30));
            int costIva = (int) ((float) ((prectot) * 0.19));
            String fecCom = this.fechTxt.getText().trim();
            String hora = this.horTxt.getText().trim();
            int iva = 19;
            TipoDePago s = (TipoDePago) this.metPagCbx.getSelectedItem();
            int idTip = s.getIdPago();

            Factura p = new Factura();
            p.setFolio(idFact);
            p.setPrecioNeto(precioNeto);
            p.setPrecioTotal(prectot);
            p.setCostoIva(costIva);
            p.setFechaCompra(fecCom);
            p.setHoraCompra(hora);
            p.setIva(iva);
            p.setTipoDePagoID(idTip);

            new FacturaDAO().ingresarFactura(p);

            //Compra
            Trabajador y = (Trabajador) this.trabCbx.getSelectedItem();
            Distribuidor dis = (Distribuidor) this.distCbx.getSelectedItem();
            int idTrab= y.getRut();
            int idDis = dis.getRut();

            Compra v = new Compra();
            v.setId(idCompra);
            v.setFolioFact(idFact);
            v.setDistribuidorRut(idDis);
            v.setTrabajadorRut(idTrab);
            
            new CompraDAO().ingresarCompra(v);
            //LibroCompra
            int idLib = k.getIdSerie();
            LibroCompra h =new LibroCompra();
            h.setIdLibro(idLib);
            h.setIdCompra(idCompra);
            
            new LibroCompraDAO().ingresarLibroCompra(h);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ingresado OK");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Ingresar una boleta");
        }
    }//GEN-LAST:event_compraBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JButton compraBtn;
    private javax.swing.JComboBox<Distribuidor> distCbx;
    private javax.swing.JTextField fechTxt;
    private javax.swing.JTextField horTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<Libro> libCbx;
    private javax.swing.JComboBox<TipoDePago> metPagCbx;
    private javax.swing.JTextField nroFactTxt;
    private javax.swing.JTextField totaTxt;
    private javax.swing.JComboBox<Trabajador> trabCbx;
    // End of variables declaration//GEN-END:variables
}
