/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.ProyectoBiblioteca.SistemaArriendo;

import cl.inacap.ProyectoBibliotecaModel.DAO.LibroDAO.LibroDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.ClienteDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.RecursosHumanosDAO.TrabajadorDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.ArriendoDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.DetalleArrDAO;
import cl.inacap.ProyectoBibliotecaModel.DAO.TransaccionessDAO.TipoDePagoDAO;
import cl.inacap.ProyectoBibliotecaModel.DTO.Libro.Libro;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Cliente;
import cl.inacap.ProyectoBibliotecaModel.DTO.RecursosHumanos.Trabajador;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.Arriendo;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.DetalleArr;
import cl.inacap.ProyectoBibliotecaModel.DTO.Transacciones.TipoDePago;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author adminclases
 */
public class SistemaArriendoFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SistemaArriendoFrame
     */
    public SistemaArriendoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        libCbx = new javax.swing.JComboBox<>();
        tipPagCbx = new javax.swing.JComboBox<>();
        cliCbx = new javax.swing.JComboBox<>();
        trabCbx = new javax.swing.JComboBox<>();
        fechaArrTxt = new javax.swing.JTextField();
        fechaDevEnTxt = new javax.swing.JTextField();
        diasArrTxt = new javax.swing.JTextField();
        diaRetrTxt = new javax.swing.JTextField();
        arrBtn = new javax.swing.JButton();
        arrTotTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nroArriTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fechDevReTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Arriendo");

        jLabel2.setText("Libro");

        jLabel3.setText("Fecha inicio Arriendo");

        jLabel4.setText("Fecha Devolucion");

        jLabel5.setText("Dias Arrendado");

        jLabel6.setText("Dias de retraso");

        jLabel7.setText("Metodo Pago");

        jLabel8.setText("Cliente");

        jLabel9.setText("Trabajador");

        tipPagCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipPagCbxActionPerformed(evt);
            }
        });

        diaRetrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaRetrTxtActionPerformed(evt);
            }
        });

        arrBtn.setText("Arrendar");
        arrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrBtnActionPerformed(evt);
            }
        });

        arrTotTxt.setEditable(false);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nroArriTxt.setEditable(false);

        jLabel10.setText("Numero Arriendo");

        jLabel11.setText("Valor por dia de arriendo");

        jLabel12.setText("Fecha Devolucion Real");

        jLabel13.setText("El valor de la multa es de 500 por dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(278, 278, 278))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(arrTotTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(diaRetrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cliCbx, 0, 238, Short.MAX_VALUE)
                                        .addComponent(tipPagCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(trabCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13)))
                            .addGap(0, 17, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(87, 87, 87)
                                .addComponent(libCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(diasArrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fechaArrTxt)
                                        .addComponent(fechaDevEnTxt)
                                        .addComponent(fechDevReTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))))
                        .addGap(137, 137, 137))))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(nroArriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroArriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(libCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fechaArrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fechaDevEnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fechDevReTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(diasArrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(diaRetrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipPagCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cliCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(trabCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrTotTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaRetrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaRetrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaRetrTxtActionPerformed

    private void tipPagCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipPagCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipPagCbxActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

        List<Libro> personas = new LibroDAO().getLibros();
        this.libCbx.removeAllItems();
        for (Libro p : personas) {
            this.libCbx.addItem(p);
        }
        List<TipoDePago> s = new TipoDePagoDAO().getTiposPagos();
        this.tipPagCbx.removeAllItems();
        for (TipoDePago p : s) {
            this.tipPagCbx.addItem(p);
        }
        List<Cliente> d = new ClienteDAO().getClientes();
        this.cliCbx.removeAllItems();
        for (Cliente p : d) {
            this.cliCbx.addItem(p);
        }
        List<Trabajador> f = new TrabajadorDAO().getTrabajadores();
        this.trabCbx.removeAllItems();
        for (Trabajador p : f) {
            this.trabCbx.addItem(p);
        }
        List<Arriendo> bols = new ArriendoDAO().getArriendos();
        for (Arriendo p : bols) {
            this.nroArriTxt.setText((p.getId() + 1) + "");
        }


    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Libro l = (Libro) this.libCbx.getSelectedItem();
        int prec = l.getPrecio();
        int total = (int) ((float) ((prec) * 0.05));
        this.arrTotTxt.setText(total + "");
        this.arrBtn.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void arrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrBtnActionPerformed
        // TODO add your handling code here:

        Libro l = (Libro) this.libCbx.getSelectedItem();
        int prec = l.getPrecio();
        int costoArrDia = (int) ((float) ((prec) * 0.05));
        this.arrTotTxt.setText(costoArrDia + "");

        try {
            List<Arriendo> bols = new ArriendoDAO().getArriendos();
            int idArr = Integer.parseInt(this.nroArriTxt.getText().trim());
            String fechArr = this.fechaArrTxt.getText().trim();
            String fechDev = this.fechaDevEnTxt.getText().trim();
            String fechaRea = this.fechDevReTxt.getText().trim();
            // total costo
            int diaArr = Integer.parseInt(this.diasArrTxt.getText().trim());
            int diaRetr = Integer.parseInt(this.diaRetrTxt.getText().trim());

            int costoTot = 0, cosArr = 0, cosMul = 0, multa = 0;
            cosArr = diaArr * costoArrDia;
            multa = diaRetr * 500;
            costoTot = cosArr + multa;

            TipoDePago g = (TipoDePago) this.tipPagCbx.getSelectedItem();
            Cliente cli = (Cliente) this.cliCbx.getSelectedItem();
            Trabajador trab = (Trabajador) this.trabCbx.getSelectedItem();

            int idpag = g.getIdPago();
            int rutCli = cli.getRut();
            int rutTrab  = trab.getRut();
            
            int iva = 19;


            //Arriendo
            

            Arriendo p = new Arriendo();
            p.setId(idArr);
            p.setCostoTotal(costoTot);
            p.setFechaArri(fechArr);
            p.setFechaDevEntr(fechDev);
            p.setFechaDevReal(fechaRea);
            p.setDiasRetraso(diaRetr);
            p.setMulta(multa);
            p.setIva(iva);
            p.setTipoPago(idpag);
            p.setClienteRut(rutCli);
            p.setTrabajadorRut(rutTrab);
            

            new ArriendoDAO().ingresarArriendo(p);
            
            //DetalleArr
            DetalleArr t = new DetalleArr();
            int idlib= l.getIdSerie();
            t.setIdArr(idArr);
            t.setIdLibro(idlib);
            
            new DetalleArrDAO().ingresarDetalleArr(t);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ingresado OK");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Ingresar una arriendo");
        }


    }//GEN-LAST:event_arrBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrBtn;
    private javax.swing.JTextField arrTotTxt;
    private javax.swing.JComboBox<Cliente> cliCbx;
    private javax.swing.JTextField diaRetrTxt;
    private javax.swing.JTextField diasArrTxt;
    private javax.swing.JTextField fechDevReTxt;
    private javax.swing.JTextField fechaArrTxt;
    private javax.swing.JTextField fechaDevEnTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<Libro> libCbx;
    private javax.swing.JTextField nroArriTxt;
    private javax.swing.JComboBox<TipoDePago> tipPagCbx;
    private javax.swing.JComboBox<Trabajador> trabCbx;
    // End of variables declaration//GEN-END:variables
}
